name: Build the API References an open a docs PR

on: workflow_call

jobs:
  docs-update-prep:
    name: Prepare for docs update
    runs-on: ubuntu-latest
    steps:
      - name: Generate a temporary branch name for docs update PR
        id: generate-branch-name
        run: |
          echo "BRANCH_NAME=temp/amplify-js-$(date +%s)" >> "$GITHUB_OUTPUT"
    outputs:
      branch_name: ${{ steps.generate-branch-name.outputs.BRANCH_NAME }}

  deploy:
    name: Publish to amplify-js docs updates
    runs-on: ubuntu-latest
    needs: docs-update-prep
    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          path: amplify-js
          # Minimal depth 0 so we can fetch all git tags.
          fetch-depth: 0
      - name: Checkout staging repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          repository: ${{ github.repository_owner }}/docs
          path: docs
          token: ${{ secrets.GH_TOKEN_AMPLIFY_JS_WRITE }}

      - name: Setup node and build the repository
        uses: ./amplify-js/.github/actions/node-and-build

      - name: Build docs references
        working-directory: ./amplify-js
        run: |
          yarn run docs

      - name: Update API references in the docs site
        working-directory: ./docs
        run: |
          yarn clean-references -- -p amplify-js
          git add .
          git commit -m "chore: Update amplify-js API references"

      - name: Create a docs PR to merge api references back into the docs site
        working-directory: ./docs
        env:
          TEMP_BRANCH_NAME: ${{ needs.docs-update-prep.outputs.branch_name }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_AMPLIFY_JS_WRITE }}
        run: |
          git checkout -b $TEMP_BRANCH_NAME
          git push origin $TEMP_BRANCH_NAME
          gh pr create -B main -H $TEMP_BRANCH_NAME --title 'chore: amplify-js api references update' --body 'Merge the api references changes from the most recent release.'          
