name: Release Verification Tests

on: workflow_call

jobs:
  prebuild-ubuntu:
    uses: ./.github/workflows/callable-prebuild-amplify-js.yml
    with:
      runs_on: ubuntu-latest
  prebuild-macos:
    uses: ./.github/workflows/callable-prebuild-amplify-js.yml
    with:
      runs_on: macos-latest
  prebuild-samples-staging:
    secrets: inherit
    uses: ./.github/workflows/callable-prebuild-samples-staging.yml
  e2e:
    runs-on: ubuntu-latest
    needs:
      - prebuild-macos
      - prebuild-ubuntu
      - prebuild-samples-staging
    steps:
      - name: Fake test to keep this test concise
        run: |
          echo "Hello world"